-- MySQL Script generated by MySQL Workbench
-- 06/17/19 15:23:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- ----------------------------------
-- Table usuario
CREATE TABLE IF NOT EXISTS `mydb`.`login`(
usuariooid int primary key auto_increment,
usuario varchar(25),
senha varchar(25)
)auto_increment = 1;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `IdPessoa` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Nacionalidade` VARCHAR(45) NOT NULL,
  `Profissao` VARCHAR(45) NOT NULL,
  `EstadoCivil` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(100) NOT NULL,
  `Sexo` VARCHAR(2) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NULL,
  `EnderecoEmpresa` VARCHAR(100) NULL,
  `Cargo` VARCHAR(45) NULL,
  `TipoEmpresa` VARCHAR(2) NULL,
  `CidadeEmpresa` VARCHAR(45) NULL,
  `NumeroEmpresa` VARCHAR(45) NULL,
  `NomeEmpresa` VARCHAR(45) NULL,
  PRIMARY KEY (`IdPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `IdVeiculo` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(4) NOT NULL,
  `Ano` VARCHAR(4) NOT NULL,
  `Chassi` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NOT NULL,
  `Placa` VARCHAR(6) NOT NULL,
  `Renavam` VARCHAR(45) NOT NULL,
  `EmNomeDe` VARCHAR(50) NOT NULL,
  `Valor` DOUBLE NULL,
  PRIMARY KEY (`IdVeiculo`),
  UNIQUE INDEX `Valor_UNIQUE` (`Valor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contrato` (
  `IdContrato` INT NOT NULL AUTO_INCREMENT,
  `ValorTotal` DECIMAL NOT NULL,
  `NumeroParcelas` INT NOT NULL,
  `ValorParcela` DECIMAL NOT NULL,
  `DataPagamento` VARCHAR(10) NOT NULL,
  `Juros` VARCHAR(45) NOT NULL,
  `Foro` VARCHAR(45) NOT NULL,
  `LocalAss` VARCHAR(45) NOT NULL,
  `DataAss` VARCHAR(10) NOT NULL,
  `Pessoa_IdPessoa` INT NOT NULL,
  `Veiculo_IdVeiculo` INT NOT NULL,
  PRIMARY KEY (`IdContrato`, `Pessoa_IdPessoa`, `Veiculo_IdVeiculo`),
  INDEX `fk_Contrato_Pessoa1_idx` (`Pessoa_IdPessoa` ASC),
  INDEX `fk_Contrato_Veiculo1_idx` (`Veiculo_IdVeiculo` ASC),
  CONSTRAINT `fk_Contrato_Pessoa1`
    FOREIGN KEY (`Pessoa_IdPessoa`)
    REFERENCES `mydb`.`Pessoa` (`IdPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contrato_Veiculo1`
    FOREIGN KEY (`Veiculo_IdVeiculo`)
    REFERENCES `mydb`.`Veiculo` (`IdVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Testemunha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Testemunha` (
  `IdTestemunha` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `RG` VARCHAR(15) NOT NULL,
  `Contrato_IdContrato` INT NOT NULL,
  PRIMARY KEY (`IdTestemunha`, `Contrato_IdContrato`),
  INDEX `fk_Testemunha_Contrato1_idx` (`Contrato_IdContrato` ASC),
  CONSTRAINT `fk_Testemunha_Contrato1`
    FOREIGN KEY (`Contrato_IdContrato`)
    REFERENCES `mydb`.`Contrato` (`IdContrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;